// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDpzHrWEAViYuJdJ2DIvqFJcBzeXnuom8',
    appId: '1:1027288925700:web:514da48f78753d8f2b9751',
    messagingSenderId: '1027288925700',
    projectId: 'finalproject-47d93',
    authDomain: 'finalproject-47d93.firebaseapp.com',
    storageBucket: 'finalproject-47d93.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB33XT_-cjhf0bs1_FZt8iBs8vi5XWBKqQ',
    appId: '1:1027288925700:android:526a9564e85f459c2b9751',
    messagingSenderId: '1027288925700',
    projectId: 'finalproject-47d93',
    storageBucket: 'finalproject-47d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGg_AH17k4t6D4JOYBYTkZXL-EYYbUbsU',
    appId: '1:1027288925700:ios:99fcfd4e259d25b92b9751',
    messagingSenderId: '1027288925700',
    projectId: 'finalproject-47d93',
    storageBucket: 'finalproject-47d93.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGg_AH17k4t6D4JOYBYTkZXL-EYYbUbsU',
    appId: '1:1027288925700:ios:99fcfd4e259d25b92b9751',
    messagingSenderId: '1027288925700',
    projectId: 'finalproject-47d93',
    storageBucket: 'finalproject-47d93.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDpzHrWEAViYuJdJ2DIvqFJcBzeXnuom8',
    appId: '1:1027288925700:web:4c477d956d12f5482b9751',
    messagingSenderId: '1027288925700',
    projectId: 'finalproject-47d93',
    authDomain: 'finalproject-47d93.firebaseapp.com',
    storageBucket: 'finalproject-47d93.appspot.com',
  );
}
